// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: proto/game.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "game";

export interface GetLevelsRequest {
  /** để check unlock status */
  auth_id: number;
}

export interface LevelSummary {
  id: number;
  name: string;
  description: string;
  is_unlocked: boolean;
  is_completed: boolean;
  challenge_count: number;
}

export interface GetLevelsResponse {
  levels: LevelSummary[];
}

export interface GetLevelDetailRequest {
  level_id: number;
  auth_id: number;
}

export interface ChallengeItem {
  id: number;
  title: string;
  /** "variable" | "condition" | "loop" */
  type: string;
  is_completed: boolean;
}

export interface GetLevelDetailResponse {
  id: number;
  name: string;
  description: string;
  /** lore của màn chơi */
  story: string;
  is_unlocked: boolean;
  challenges: ChallengeItem[];
}

export interface GetChallengeRequest {
  challenge_id: number;
}

export interface GetChallengeResponse {
  id: number;
  level_id: number;
  title: string;
  description: string;
  /** "variable" | "condition" | "loop" */
  type: string;
  /** code mẫu cho người chơi */
  starter_code: string;
  max_score: number;
  hint_count: number;
}

export interface GetHintRequest {
  challenge_id: number;
  /** 0-based, tăng dần theo lần gợi ý */
  hint_index: number;
}

export interface GetHintResponse {
  hint: string;
  is_last: boolean;
}

export interface SubmitAnswerRequest {
  auth_id: number;
  challenge_id: number;
  code: string;
  /** "python" | "javascript" */
  language: string;
}

export interface SubmitAnswerResponse {
  passed: boolean;
  score: number;
  /** "Đúng rồi!" hoặc mô tả lỗi */
  feedback: string;
  /** dùng để tính bonus Màn 3 */
  line_count: number;
  execution_ms: number;
  test_results: TestResult[];
}

export interface TestResult {
  input: string;
  expected: string;
  actual: string;
  passed: boolean;
}

export interface GetProgressRequest {
  auth_id: number;
}

export interface LevelProgress {
  level_id: number;
  level_name: string;
  is_completed: boolean;
  challenges_done: number;
  challenges_total: number;
  score: number;
  /** seconds */
  time_spent: number;
}

export interface GetProgressResponse {
  levels: LevelProgress[];
  total_score: number;
  levels_completed: number;
}

export interface StartLevelRequest {
  auth_id: number;
  level_id: number;
}

export interface StartLevelResponse {
  success: boolean;
  /** ISO8601 */
  started_at: string;
}

export interface CompleteLevelRequest {
  auth_id: number;
  level_id: number;
  score: number;
  /** seconds */
  time_spent: number;
  level_name: string;
}

export interface CompleteLevelResponse {
  success: boolean;
  next_level_unlocked: boolean;
  next_level_id: number;
}

export interface RunCodeRequest {
  code: string;
  /** "python" | "javascript" */
  language: string;
  /** input nếu có */
  stdin: string;
}

export interface RunCodeResponse {
  stdout: string;
  stderr: string;
  exit_code: number;
  execution_ms: number;
  timed_out: boolean;
}

export interface ValidateCodeRequest {
  challenge_id: number;
  code: string;
  language: string;
}

export interface ValidateCodeResponse {
  passed: boolean;
  feedback: string;
  score: number;
  line_count: number;
  test_results: TestResult[];
}

/** ----- Admin: Level ----- */
export interface AdminCreateLevelRequest {
  name: string;
  description: string;
  story: string;
  order: number;
}

export interface AdminCreateLevelResponse {
  success: boolean;
  id: number;
}

export interface AdminUpdateLevelRequest {
  id: number;
  name: string;
  description: string;
  story: string;
  order: number;
  is_active: boolean;
}

export interface AdminUpdateLevelResponse {
  success: boolean;
}

export interface AdminDeleteLevelRequest {
  id: number;
}

export interface AdminDeleteLevelResponse {
  success: boolean;
}

export interface AdminGetAllLevelsRequest {
}

export interface AdminLevelItem {
  id: number;
  name: string;
  description: string;
  story: string;
  order: number;
  is_active: boolean;
  challenge_count: number;
}

export interface AdminGetAllLevelsResponse {
  levels: AdminLevelItem[];
}

/** ----- Admin: Challenge ----- */
export interface AdminCreateChallengeRequest {
  level_id: number;
  title: string;
  description: string;
  type: string;
  starter_code: string;
  max_score: number;
  order: number;
}

export interface AdminCreateChallengeResponse {
  success: boolean;
  id: number;
}

export interface AdminUpdateChallengeRequest {
  id: number;
  title: string;
  description: string;
  type: string;
  starter_code: string;
  max_score: number;
  order: number;
}

export interface AdminUpdateChallengeResponse {
  success: boolean;
}

export interface AdminDeleteChallengeRequest {
  id: number;
}

export interface AdminDeleteChallengeResponse {
  success: boolean;
}

export interface AdminGetChallengesByLevelRequest {
  level_id: number;
}

export interface AdminChallengeItem {
  id: number;
  title: string;
  type: string;
  description: string;
  starter_code: string;
  max_score: number;
  order: number;
  hint_count: number;
}

export interface AdminGetChallengesByLevelResponse {
  challenges: AdminChallengeItem[];
}

/** ----- Admin: Hint ----- */
export interface AdminCreateHintRequest {
  challenge_id: number;
  content: string;
  index: number;
}

export interface AdminCreateHintResponse {
  success: boolean;
  id: number;
}

export interface AdminDeleteHintRequest {
  id: number;
}

export interface AdminDeleteHintResponse {
  success: boolean;
}

export interface AdminGetHintsByChallengeRequest {
  challenge_id: number;
}

export interface AdminHintItem {
  id: number;
  content: string;
  index: number;
}

export interface AdminGetHintsByChallengeResponse {
  hints: AdminHintItem[];
}

/** ----- Admin: Test Case ----- */
export interface AdminCreateTestCaseRequest {
  challenge_id: number;
  input: string;
  expected_output: string;
  order: number;
}

export interface AdminCreateTestCaseResponse {
  success: boolean;
  id: number;
}

export interface AdminDeleteTestCaseRequest {
  id: number;
}

export interface AdminDeleteTestCaseResponse {
  success: boolean;
}

export interface AdminGetTestCasesByChallengeRequest {
  challenge_id: number;
}

export interface AdminTestCaseItem {
  id: number;
  input: string;
  expected_output: string;
  order: number;
}

export interface AdminGetTestCasesByChallengeResponse {
  test_cases: AdminTestCaseItem[];
}

export const GAME_PACKAGE_NAME = "game";

export interface GameServiceClient {
  /** Level */

  getLevels(request: GetLevelsRequest, metadata?: Metadata): Observable<GetLevelsResponse>;

  getLevelDetail(request: GetLevelDetailRequest, metadata?: Metadata): Observable<GetLevelDetailResponse>;

  /** Challenge */

  getChallenge(request: GetChallengeRequest, metadata?: Metadata): Observable<GetChallengeResponse>;

  getHint(request: GetHintRequest, metadata?: Metadata): Observable<GetHintResponse>;

  submitAnswer(request: SubmitAnswerRequest, metadata?: Metadata): Observable<SubmitAnswerResponse>;

  /** Progress */

  getProgress(request: GetProgressRequest, metadata?: Metadata): Observable<GetProgressResponse>;

  startLevel(request: StartLevelRequest, metadata?: Metadata): Observable<StartLevelResponse>;

  completeLevel(request: CompleteLevelRequest, metadata?: Metadata): Observable<CompleteLevelResponse>;

  /** Code execution */

  runCode(request: RunCodeRequest, metadata?: Metadata): Observable<RunCodeResponse>;

  validateCode(request: ValidateCodeRequest, metadata?: Metadata): Observable<ValidateCodeResponse>;

  /** Admin */

  adminCreateLevel(request: AdminCreateLevelRequest, metadata?: Metadata): Observable<AdminCreateLevelResponse>;

  adminUpdateLevel(request: AdminUpdateLevelRequest, metadata?: Metadata): Observable<AdminUpdateLevelResponse>;

  adminDeleteLevel(request: AdminDeleteLevelRequest, metadata?: Metadata): Observable<AdminDeleteLevelResponse>;

  adminGetAllLevels(request: AdminGetAllLevelsRequest, metadata?: Metadata): Observable<AdminGetAllLevelsResponse>;

  adminCreateChallenge(
    request: AdminCreateChallengeRequest,
    metadata?: Metadata,
  ): Observable<AdminCreateChallengeResponse>;

  adminUpdateChallenge(
    request: AdminUpdateChallengeRequest,
    metadata?: Metadata,
  ): Observable<AdminUpdateChallengeResponse>;

  adminDeleteChallenge(
    request: AdminDeleteChallengeRequest,
    metadata?: Metadata,
  ): Observable<AdminDeleteChallengeResponse>;

  adminGetChallengesByLevel(
    request: AdminGetChallengesByLevelRequest,
    metadata?: Metadata,
  ): Observable<AdminGetChallengesByLevelResponse>;

  adminCreateHint(request: AdminCreateHintRequest, metadata?: Metadata): Observable<AdminCreateHintResponse>;

  adminDeleteHint(request: AdminDeleteHintRequest, metadata?: Metadata): Observable<AdminDeleteHintResponse>;

  adminGetHintsByChallenge(
    request: AdminGetHintsByChallengeRequest,
    metadata?: Metadata,
  ): Observable<AdminGetHintsByChallengeResponse>;

  adminCreateTestCase(
    request: AdminCreateTestCaseRequest,
    metadata?: Metadata,
  ): Observable<AdminCreateTestCaseResponse>;

  adminDeleteTestCase(
    request: AdminDeleteTestCaseRequest,
    metadata?: Metadata,
  ): Observable<AdminDeleteTestCaseResponse>;

  adminGetTestCasesByChallenge(
    request: AdminGetTestCasesByChallengeRequest,
    metadata?: Metadata,
  ): Observable<AdminGetTestCasesByChallengeResponse>;
}

export interface GameServiceController {
  /** Level */

  getLevels(request: GetLevelsRequest, metadata?: Metadata): Observable<GetLevelsResponse>;

  getLevelDetail(request: GetLevelDetailRequest, metadata?: Metadata): Observable<GetLevelDetailResponse>;

  /** Challenge */

  getChallenge(request: GetChallengeRequest, metadata?: Metadata): Observable<GetChallengeResponse>;

  getHint(request: GetHintRequest, metadata?: Metadata): Observable<GetHintResponse>;

  submitAnswer(request: SubmitAnswerRequest, metadata?: Metadata): Observable<SubmitAnswerResponse>;

  /** Progress */

  getProgress(request: GetProgressRequest, metadata?: Metadata): Observable<GetProgressResponse>;

  startLevel(request: StartLevelRequest, metadata?: Metadata): Observable<StartLevelResponse>;

  completeLevel(request: CompleteLevelRequest, metadata?: Metadata): Observable<CompleteLevelResponse>;

  /** Code execution */

  runCode(request: RunCodeRequest, metadata?: Metadata): Observable<RunCodeResponse>;

  validateCode(request: ValidateCodeRequest, metadata?: Metadata): Observable<ValidateCodeResponse>;

  /** Admin */

  adminCreateLevel(request: AdminCreateLevelRequest, metadata?: Metadata): Observable<AdminCreateLevelResponse>;

  adminUpdateLevel(request: AdminUpdateLevelRequest, metadata?: Metadata): Observable<AdminUpdateLevelResponse>;

  adminDeleteLevel(request: AdminDeleteLevelRequest, metadata?: Metadata): Observable<AdminDeleteLevelResponse>;

  adminGetAllLevels(request: AdminGetAllLevelsRequest, metadata?: Metadata): Observable<AdminGetAllLevelsResponse>;

  adminCreateChallenge(
    request: AdminCreateChallengeRequest,
    metadata?: Metadata,
  ): Observable<AdminCreateChallengeResponse>;

  adminUpdateChallenge(
    request: AdminUpdateChallengeRequest,
    metadata?: Metadata,
  ): Observable<AdminUpdateChallengeResponse>;

  adminDeleteChallenge(
    request: AdminDeleteChallengeRequest,
    metadata?: Metadata,
  ): Observable<AdminDeleteChallengeResponse>;

  adminGetChallengesByLevel(
    request: AdminGetChallengesByLevelRequest,
    metadata?: Metadata,
  ): Observable<AdminGetChallengesByLevelResponse>;

  adminCreateHint(request: AdminCreateHintRequest, metadata?: Metadata): Observable<AdminCreateHintResponse>;

  adminDeleteHint(request: AdminDeleteHintRequest, metadata?: Metadata): Observable<AdminDeleteHintResponse>;

  adminGetHintsByChallenge(
    request: AdminGetHintsByChallengeRequest,
    metadata?: Metadata,
  ): Observable<AdminGetHintsByChallengeResponse>;

  adminCreateTestCase(
    request: AdminCreateTestCaseRequest,
    metadata?: Metadata,
  ): Observable<AdminCreateTestCaseResponse>;

  adminDeleteTestCase(
    request: AdminDeleteTestCaseRequest,
    metadata?: Metadata,
  ): Observable<AdminDeleteTestCaseResponse>;

  adminGetTestCasesByChallenge(
    request: AdminGetTestCasesByChallengeRequest,
    metadata?: Metadata,
  ): Observable<AdminGetTestCasesByChallengeResponse>;
}

export function GameServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getLevels",
      "getLevelDetail",
      "getChallenge",
      "getHint",
      "submitAnswer",
      "getProgress",
      "startLevel",
      "completeLevel",
      "runCode",
      "validateCode",
      "adminCreateLevel",
      "adminUpdateLevel",
      "adminDeleteLevel",
      "adminGetAllLevels",
      "adminCreateChallenge",
      "adminUpdateChallenge",
      "adminDeleteChallenge",
      "adminGetChallengesByLevel",
      "adminCreateHint",
      "adminDeleteHint",
      "adminGetHintsByChallenge",
      "adminCreateTestCase",
      "adminDeleteTestCase",
      "adminGetTestCasesByChallenge",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("GameService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("GameService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const GAME_SERVICE_NAME = "GameService";
