// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: proto/user.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "player";

export interface GetProfileRequest {
  auth_id: number;
}

export interface GetProfileResponse {
  auth_id: number;
  username: string;
  realname: string;
  avatar: string;
  total_score: number;
  rank: number;
}

export interface UpdateProfileRequest {
  auth_id: number;
  avatar: string;
  realname: string;
}

export interface UpdateProfileResponse {
  success: boolean;
}

export interface AddScoreRequest {
  auth_id: number;
  level_id: number;
  score: number;
  /** seconds */
  time_spent: number;
  level_name: string;
}

export interface AddScoreResponse {
  success: boolean;
  total_score: number;
}

export interface GetScoresRequest {
  auth_id: number;
}

export interface ScoreEntry {
  level_id: number;
  level_name: string;
  score: number;
  time_spent: number;
  /** ISO8601 */
  completed_at: string;
}

export interface GetScoresResponse {
  scores: ScoreEntry[];
}

export interface GetLeaderboardRequest {
  /** default 10 */
  limit: number;
  offset: number;
}

export interface LeaderboardEntry {
  rank: number;
  auth_id: number;
  username: string;
  avatar: string;
  total_score: number;
}

export interface GetLeaderboardResponse {
  entries: LeaderboardEntry[];
  total: number;
}

export interface CreateProfileRequest {
  auth_id: number;
  username: string;
  email: string;
  realname: string;
}

export interface CreateProfileResponse {
  success: boolean;
}

export const PLAYER_PACKAGE_NAME = "player";

export interface PlayerServiceClient {
  createProfile(request: CreateProfileRequest, metadata?: Metadata): Observable<CreateProfileResponse>;

  getProfile(request: GetProfileRequest, metadata?: Metadata): Observable<GetProfileResponse>;

  updateProfile(request: UpdateProfileRequest, metadata?: Metadata): Observable<UpdateProfileResponse>;

  getLeaderboard(request: GetLeaderboardRequest, metadata?: Metadata): Observable<GetLeaderboardResponse>;

  addScore(request: AddScoreRequest, metadata?: Metadata): Observable<AddScoreResponse>;

  getScores(request: GetScoresRequest, metadata?: Metadata): Observable<GetScoresResponse>;
}

export interface PlayerServiceController {
  createProfile(request: CreateProfileRequest, metadata?: Metadata): Observable<CreateProfileResponse>;

  getProfile(request: GetProfileRequest, metadata?: Metadata): Observable<GetProfileResponse>;

  updateProfile(request: UpdateProfileRequest, metadata?: Metadata): Observable<UpdateProfileResponse>;

  getLeaderboard(request: GetLeaderboardRequest, metadata?: Metadata): Observable<GetLeaderboardResponse>;

  addScore(request: AddScoreRequest, metadata?: Metadata): Observable<AddScoreResponse>;

  getScores(request: GetScoresRequest, metadata?: Metadata): Observable<GetScoresResponse>;
}

export function PlayerServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createProfile",
      "getProfile",
      "updateProfile",
      "getLeaderboard",
      "addScore",
      "getScores",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PlayerService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PlayerService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PLAYER_SERVICE_NAME = "PlayerService";
